steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - europe-west1-docker.pkg.dev/book-publishing-backend/backend-repo/backend
      - .

images:
  - europe-west1-docker.pkg.dev/book-publishing-backend/backend-repo/backend
