spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:root}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false

auth:
  users:
    - username: ${LOCAL_ADMIN_NAME}
      password: ${LOCAL_ADMIN_PASSWORD}
      roles:
        - ADMIN
        - USER
    - username: ${LOCAL_USER_NAME}
      password: ${LOCAL_USER_PASSWORD}
      roles:
        - USER

logging:
  level:
    org.cescfe.bookpublishing: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
