name: Pull Request Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-pull-request:
    runs-on: ubuntu-latest
    env:
      GITHUB_USERNAME: ${{ github.actor }}
      TOKEN_PAT: ${{ secrets.TOKEN_PAT }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - run: chmod +x gradlew

      - name: Download Spotless dependencies
        run: ./gradlew spotlessInternalRegisterDependencies --build-cache
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2048m -Dorg.gradle.caching=true

      - name: Run Spotless check
        run: ./gradlew spotlessCheck --build-cache
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2048m -Dorg.gradle.caching=true -Dorg.gradle.parallel=true

      - name: Run all tests
        run: ./gradlew test --build-cache --parallel
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2048m -Dorg.gradle.caching=true -Dorg.gradle.parallel=true
