name: Pull Request Validation

permissions:
  contents: read
  id-token: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    uses: ./.github/workflows/setup-gcp-java.yml
    with:
      gcp_service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      gcp_wif_provider: ${{ secrets.GCP_WIF_PROVIDER }}

  build-test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Run Spotless check
        run: ./gradlew spotlessCheck --build-cache

      - name: Run all tests
        run: ./gradlew test --parallel --build-cache
