name: Setup GCP + Java

on:
  workflow_call:
    inputs:
      gcp_service_account:
        required: true
        type: string
      gcp_wif_provider:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ inputs.gcp_wif_provider }}
          service_account: ${{ inputs.gcp_service_account }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew
